# Taken from https://github.com/nvim-neorg/neorg/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml
# and modified

name: Bug Report
description: Report a bug
labels: [bug]
body:

  - type: checkboxes
    id: faq-prerequisite
    attributes:
      label: Prerequisites
      options:
        - label: I am using the minimum required version of Neovim
          required: true
        - label: I am using the latest version of the plugin
          required: true

  - type: input
    attributes:
      label: "Neovim Version"
      description: "`nvim --version`:"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Plugin config"
      description: |
        - Copy your entire config for the plugin
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "A description of actual behavior. Can contain mages or videos."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Please describe how we can reproduce the issue."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Potentially conflicting plugins"
      description: "Other plugins you are using which you think could potentially be conflicting?."

  - type: textarea
    attributes:
      label: "Other information"
      description: "Other information that could be helpful with debugging."

  - type: dropdown
    id: help
    attributes:
      label: "Help"
      description: "Would you be able to resolve this issue by submitting a pull request?"
      options:
        - "Yes"
        - "Yes, but I don't know how to start. I would need guidance (check question below)"
        - "No"

  - type: textarea
    attributes:
      label: "Implementation help"
      description: "If you selected yes in the last question please specify what you would need help with in order to resolve the issue."
